### ISSUE TITLE
时间变晚也发个邮件提醒吧？

### ISSUE THREAD

**Issue by YonsiG** [Trinkle23897/us-visa#10]
如题，跪谢

**Comment by Trinkle23897** [comment]
?意义何在

**Comment by YonsiG** [comment]
因为每次收到邮件之后以为时间变早了激动地点开网页发现又回去了。。
我现在想蹲早一点的B签成都，但是如果上海8月的快没了的话还是约个上海保险着……所以既关注成都有没有变早和上海有没有变晚

**Comment by Trinkle23897** [comment]
但是其实点进去/visa网页check一下也不会花多少时间吧……？
无非这几种情况：
1. 如果7:49收到邮件，你正在cgifederal里面蹲，那点进去直接抢就行
2. 如果7:49收到邮件，你没开cgifederal，那多半也抢不到，直接忽视就行
3. 如果7:49收到邮件，你在干别的事，那反正都不会当时就点进去看，等到后面统一check一下看看图标就行
4. 如果不是x:49收到邮件，那多半是批量放名额，有至少半小时窗口期，够你抢到了

**Comment by Trinkle23897** [comment]
而且如果加了上升沿，发一坨邮件下来还要挨个去看哪个是下降哪个是上升，费脑
