### ISSUE TITLE
订阅邮件未收到提醒

### ISSUE THREAD

**Issue by wgb14** [Trinkle23897/us-visa#19]
订阅沈阳f1，日期设置8月1日，今天9：48收到了邮件提醒，18：48没有收到，垃圾邮件里也没有。不知道是哪里出了问题

**Comment by Trinkle23897** [comment]
新版爬虫有些小问题，下午成都也是，我在修
涉及到线程冲突读写的问题……

**Comment by wgb14** [comment]
辛苦！谢谢！

**Comment by Trinkle23897** [comment]
不对，沈阳六点48发成功了。。。你的邮箱就是主页上面outlook那个……？

**Comment by wgb14** [comment]
我的订阅邮箱是foxmail

**Comment by Trinkle23897** [comment]
我这边显示也是发成功了……和我的gmail一起发的，我gmail收到了

**Comment by wgb14** [comment]
那就应该不是提醒服务的问题了
奇怪了😂邮件会在半路丢了么

**Comment by Trinkle23897** [comment]
昨天好像有个qq邮箱用户也报告了这件事……感觉玄学

**Comment by Trinkle23897** [comment]
> 那就应该不是提醒服务的问题了
> 奇怪了邮件会在半路丢了么

没事没事，毕竟还开了QQ和TG，不放心的话可以加一下保险点
