### ISSUE TITLE
Crawling with Tor

### ISSUE THREAD

**Issue by kenziyuliu** [Trinkle23897/us-visa#2]
I haven't tried this myself before, but have you considered crawling with [Tor](https://stem.torproject.org/) to avoid IP address blocking?

**Comment by Trinkle23897** [comment]
不好说，我也没用过tor，但是现在看起来间隔一到两个小时是一定不会被封的

**Comment by Trinkle23897** [comment]
之前是我代码写搓了，改完之后可以无限量爬，现在暂时设置成200s间隔

**Comment by kenziyuliu** [comment]
可以的👍
