### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by zhengqigao** [Trinkle23897/us-visa#21]
Hi, thanks for the brilliant website. How about adding additional features so people can report their visa status?

**Comment by Trinkle23897** [comment]
But this is exactly the same as https://checkee.info/
![2020-05-31 12-18-44 的屏幕截图](https://user-images.githubusercontent.com/8189182/83344403-0d4f8500-a339-11ea-990b-10aa36bd90b7.png)
Click the last tag "签证结果统计" and you will be directed to that website.

**Comment by zhengqigao** [comment]
Yeah, I know that website. But here can we add extra factors, and only focus on J/F VISA? That website is too general, and even universities sometimes are N/A. Also, if I understood right, people sometimes might forgot to update their case on that website (e.g., forgetting to write when they get issued).
