### ISSUE TITLE
'tuixue.online/visa2/F/成都/2020/06/09'页面是没有实时更新吗

### ISSUE THREAD

**Issue by Yiyiyimu** [Trinkle23897/us-visa#23]
visa.json没有读懂。。就在爬城市每天的这个界面，但好像这个网页是更新优先级比较低吗，下午16:48的58才爬到变了。还有就是想问一下visa.json应该怎么爬orz

**Comment by Trinkle23897** [comment]
visa.json就是”{city}-{date}”: {time}的结构，visa.json和你说的这个文本文件是同步更新的，是最先更新，网页图表是根据这俩生成的
感觉你是不是缓存了...理论上不应该这样

**Comment by Yiyiyimu** [comment]
嗯感觉应该是缓存了，刚好这个48又更新了，爬虫爬的就还是没有变化的。多谢多谢

**Comment by Yiyiyimu** [comment]
唔想问一下selenium怎么可以强制绕过缓存刷新，试了无痕模式和`driver.execute_script("location.reload(true);")`都失败了
现在的方法就只有不断重启driver。。。这样最快刷新速度会降到7s/次，感觉不太够

**Comment by Trinkle23897** [comment]
别selenium拉，那样很慢。
直接python里面request.get(网址)就行

**Comment by Yiyiyimu** [comment]
噢噢还可以这样，多谢！
