### ISSUE TITLE
破解验证码

### ISSUE THREAD

**Issue by Trinkle23897** [Trinkle23897/us-visa#7]
目前有大概2000张带标注的验证码（[数据](https://github.com/Trinkle23897/us-visa/tree/master/visa2/log)），一天大概增加200张这样。我写了份[代码](https://github.com/Trinkle23897/us-visa/blob/master/visa2/captcha.py)发现overfit严重，换了model也不行

**Comment by Trinkle23897** [comment]
https://github.com/dee1024/pytorch-captcha-recognition.git 这个试过了，不行

**Comment by thekingofcity** [comment]
不知道有没有考虑过第三方服务咳咳, 5位英文一次是0.012元, 一小时一次的话一天成本也可以忽略不计?

**Comment by Trinkle23897** [comment]
推荐一下？

**Comment by thekingofcity** [comment]
[云打码](http://yundama.com)

**Comment by Trinkle23897** [comment]
> [云打码](http://yundama.com)

有没有ubuntu友好的……不想跑dll

**Comment by lvyaojia** [comment]
http://www.fateadm.com/  
可通过 API 调用进行识别 http://docs.fateadm.com/web/#/1?page_id=6

我简单测了几张图都成功识别了，我账户有积分，可以 share API key 给你 （发你邮箱）

**Comment by Trinkle23897** [comment]
> http://www.fateadm.com/
> 可通过 API 调用进行识别 http://docs.fateadm.com/web/#/1?page_id=6
> 
> 我简单测了几张图都成功识别了，我账户有积分，可以 share API key 给你 （发你邮箱）

价格大概多少？一个积分一块钱吗
我明天试试

**Comment by lvyaojia** [comment]
> > http://www.fateadm.com/
> > 可通过 API 调用进行识别 http://docs.fateadm.com/web/#/1?page_id=6
> > 我简单测了几张图都成功识别了，我账户有积分，可以 share API key 给你 （发你邮箱）
> 
> 价格大概多少？一个积分一块钱吗
> 我明天试试

![image](https://user-images.githubusercontent.com/559386/79758758-639bd200-8350-11ea-9a25-5a61c239098b.png)

10万次那档，0.5 分钱一次。 key 发你了，可以试试。

**Comment by thekingofcity** [comment]
> 
> 
> > [云打码](http://yundama.com)
> 
> 有没有ubuntu友好的……不想跑dll

手头有python3的实现, 不知道算不算ubuntu友好 :)

**Comment by Trinkle23897** [comment]
> > > [云打码](http://yundama.com)
> > 
> > 
> > 有没有ubuntu友好的……不想跑dll
> 
> 手头有python3的实现, 不知道算不算ubuntu友好 :)

我还是用feifei吧（看起来他们靠谱一些

**Comment by WenheLI** [comment]
一个小思路，先把验证码做个简单分割，再对单字识别。现在主要还是数据量太小了。。。

**Comment by jojo23333** [comment]
数据量有点小了？可以考虑mnist pretrain一下？或者模拟生成一下类似style的验证码然后transfer learning一下
