### ISSUE TITLE
Newest Fetch time doesn't show up on appointment page

### ISSUE THREAD

**Issue by eziosudo** [Trinkle23897/us-visa#87]
Today(2/2) I get the Newest Fetch time of Shanghai as 2/27, but I cannot see it in my appointment page, the earliest time is 4/20. Is that possible this date is invalid due to the "Date Ahead" because it should be made 37~71 days in advance? 

你好，想请教一个问题，我今天(2/2)获取到L签证最新的可预约时间是2/27，但是我到签证页查看发现并没有这个日期，我可以约的最早日期是4/20，如果排除掉被其他人预约了的可能，这个情况是否和Date Ahead有关？因为这天的面签必须提前37～71天预约？

`appointments should be made 37 ~ 71 days in advance`

<img width="1088" alt="Screenshot 2023-02-04 at 19 53 52" src="https://user-images.githubusercontent.com/54128896/216766859-e38f2711-aff6-4a7b-84ff-90c2d34f7367.png">

**Comment by Trinkle23897** [comment]
就是被别人抢了...

**Comment by eziosudo** [comment]
> 就是被别人抢了...

因为我是1分钟之内去看预约页面上没有，tuixue最新时间刷出来的还是2/27，之后tuixue重新Fetch还是2/27，我还是看不到 T.T

现在最新的是 3/2，时间8:49，我8点50上去看最新只有4/20。这么难抢吗 0 0
<img width="980" alt="image" src="https://user-images.githubusercontent.com/54128896/216795927-329704ca-b21d-4699-bb1e-b7a69e9f6f0e.png">

**Comment by eziosudo** [comment]
时间9点24，

<img width="985" alt="image" src="https://user-images.githubusercontent.com/54128896/216796937-a5fdd7ae-66eb-415f-80a8-c27a2f00a01a.png">

我同时间去看预约 最早4/20。
<img width="636" alt="image" src="https://user-images.githubusercontent.com/54128896/216796954-72ca6681-25b3-4ea4-866a-a621684d9b39.png">

**Comment by eziosudo** [comment]
重新注册了一个账号，发现最早可预约的时间的确是3/2。
<img width="470" alt="image" src="https://user-images.githubusercontent.com/54128896/216820385-db182c41-4150-444b-ad87-2e73344a824e.png">

我是reschedule，重新预约的页面无法把月份往前调，也不知道是为什么了。但数据是对的，我关单子了，多谢大佬。
<img width="621" alt="image" src="https://user-images.githubusercontent.com/54128896/216820281-9b84de4a-9211-4b2b-91a1-86b315699de9.png">
